# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute_LH_cpp
#'
#' This function makes the matrices L and H for all the genes with a new method.
#'
#' @param data_ctrl A numeric matrix with the genes expressions for each patient. Must be sort by the median.
#' @param threshold The proportion of genes that must be under or above the gene.
#' @param size_max The maximum number of L and H genes for each gene..
#'
#' @return This function returns a list of two logical matrices :
#' the L matrix, with the id of closest genes with a lower expression,
#' the H Matrix with the id of closest genes with a higher expression,
#' And the n string vector with the genes names.
#'
#' @export
compute_LH_cpp <- function(data_ctrl, threshold, size_max) {
    .Call(`_penda_compute_LH_cpp`, data_ctrl, threshold, size_max)
}

#' compute_LH_cppNA
#'
#' This function makes the matrices L and H for all the genes without count NA values.
#'
#' @param data_ctrl A numeric matrix with the genes expressions for each patient.
#' @param threshold The proportion of genes that must be under or above the gene.
#' @param nbNA The number of NA for each gene.
#' @param size_max The maximum number of L and H genes for each gene..
#'
#' @return This function returns a list of two logical matrices :
#' the L matrix, with the id of closest genes with a lower expression,
#' the H Matrix with the id of closest genes with a higher expression,
#' And the n string vector with the genes names.
#'
#' @export
compute_LH_cppNA <- function(data_ctrl, threshold, nbNA, size_max) {
    .Call(`_penda_compute_LH_cppNA`, data_ctrl, threshold, nbNA, size_max)
}

